import { describe, expect, it } from 'vitest';
import { extractInstalls, mergeSuggestions, renderContainerfile } from './containerfile-suggest.ts';

describe('containerfile suggestions', () => {
  it('captures system-wide installs, which is what an image is for', () => {
    expect(extractInstalls('apt-get install -y python3.7 libpq-dev')).toEqual([
      {
        manager: 'apt',
        command: 'apt-get update && apt-get install -y --no-install-recommends python3.7 libpq-dev && rm -rf /var/lib/apt/lists/*',
      },
    ]);
    expect(extractInstalls('npm i -g typescript')[0]?.command).toBe('npm install -g typescript');
    expect(extractInstalls('pnpm add -g vercel')[0]?.command).toBe('pnpm add -g vercel');
    expect(extractInstalls('pipx install poetry')[0]?.command).toBe('pipx install poetry');
  });

  it('IGNORES a project\'s own dependency installs — those belong to the repo, not the image', () => {
    // The distinction the whole feature rests on. Baking these in produces an
    // image that is stale the moment a dependency changes, and duplicates what
    // the lockfile already says.
    expect(extractInstalls('npm install')).toEqual([]);
    expect(extractInstalls('pnpm install --frozen-lockfile')).toEqual([]);
    expect(extractInstalls('npm install react')).toEqual([]);
    expect(extractInstalls('pip install -r requirements.txt')).toEqual([]);
    expect(extractInstalls('pip install -e .')).toEqual([]);
  });

  it('reads every clause of a chained command', () => {
    const found = extractInstalls('apt-get update && apt-get install -y git curl && npm i -g pnpm@9');
    expect(found.map((f) => f.manager)).toEqual(['apt', 'npm']);
    expect(found[1]?.command).toBe('npm install -g pnpm@9');
  });

  it('drops sudo and flags rather than treating them as packages', () => {
    const found = extractInstalls('sudo apt-get install -y --no-install-recommends ripgrep');
    expect(found[0]?.command).toContain('ripgrep');
    expect(found[0]?.command).not.toContain('sudo');
    expect(found[0]?.command).not.toContain('--no-install-recommends ripgrep --');
  });

  it('renders apt non-interactively and cleans its lists', () => {
    // A Containerfile that prompts hangs the build; one that keeps lists bloats
    // the image. Both are silent failures at build time, not run time.
    const cmd = extractInstalls('apt install postgresql-client')[0]?.command ?? '';
    expect(cmd).toContain('-y');
    expect(cmd).toContain('rm -rf /var/lib/apt/lists/*');
  });

  it('merges without duplicating, keeping first-seen order', () => {
    const a = extractInstalls('npm i -g typescript');
    const b = extractInstalls('npm i -g typescript');
    const c = extractInstalls('gem install bundler');
    expect(mergeSuggestions(mergeSuggestions(a, b), c)).toHaveLength(2);
    expect(mergeSuggestions(a, c)[0]?.command).toBe('npm install -g typescript');
  });

  it('builds FROM the cezar base so the agent CLI is inherited, not restated', () => {
    const file = renderContainerfile(extractInstalls('apt-get install -y python3.7'));
    expect(file).toContain('FROM localhost/cezar-agent/base:latest');
    expect(file).toContain('RUN apt-get update && apt-get install -y --no-install-recommends python3.7');
    // The reader must know where this came from and when it takes effect.
    expect(file).toContain('Generated by cezar');
    expect(file).toContain('NEXT task');
  });
});
